spring:
  application:
    name: jchatmind
  datasource:
    url: jdbc:postgresql://localhost:5432/jchatmind
    username: postgres
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 1598826374@qq.com
    password: ${MAIL_PASSWORD:wkjydaedaibbfdja}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:sk-2188cc99eb2e4ecc8558462784667ede}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY:3a14463a544f4c80844dd18a563a9d8b.bo4YX6sBjstlHwoD}
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6v
mybatis:
  type-aliases-package: com.kama.jchatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.kama.jchatmind.typehandler

document:
  storage:
    base-path: ./data/documents

reranker:
  base-url: http://127.0.0.1:8001
